language: node_js

sudo: required

node_js:
  - 8.9.0

cache:
  directories:
    - node_modules

install:
  - npm install

before_script:

script:
  - gulp scss

after_script:
  - git init
  - git config user.name "${NAME}"
  - git config user.email "${EMAIL}"
  - git checkout -b ${P_BRANCH}
  - git add *
  - git commit -m "Update branch"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH}



