# 指定语言环境
language: node_js
# 指定需要sudo权限
sudo: required
# 指定node_js版本
node_js:
  - 8.9.0
# 指定缓存模块，可选。缓存可加快编译速度。
cache:
  directories:
    - node_modules

# 指定博客源码分支，因人而异。hexo博客源码托管在独立repo则不用设置此项
branches:
  only:
    - master

# 执行清缓存，生成网页操作
script:
  - git config user.name "${NAME}"
  - git config user.email "${EMAIL}"
  - git branch gh-page
  
# End: Build LifeCycle