language: node_js

sudo: required

node_js:
  - 8.9.0

cache:
  directories:
    - node_modules

branches:
  only:
    - master

install:
  - npm install

before_script:

script:


after_script:
  - git init
  - git config user.name "${NAME}"
  - git config user.email "${EMAIL}"
  - git add *
  - git commit -m "Update branch"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH}



